### ISSUE TITLE
Solution basesection

### ISSUE THREAD

**Issue by budschi** [FAIRmat-NFDI/nomad-material-processing#10]
we need a basesection that handles solutions. That means adding Components to CompositeSystem by volume and weight. E.g.:

```
Solution 1: 
  - 0.1004 g (NH4)2HPO4 
  - 20 ml H2O
```
So far we can only add Components by weight.

**Comment by aalbino2** [comment]
basesection development. @budschi @hampusnasstrom 

doublecheck:
- hysprint Micha
- Chemotion

```
Solution_preparation(Activity):
  m_def: template
  name:
  description:
  atmosphere:
  intended_sample_conc:
  obtained_conc:
  intended_tot_volume:
  obtained_tot_volume:
  steps:
    weighing:
      component(Component): 
      alias: (default value)
      container_mass:
      net_mass:
      brutto_mass:
      molecular_weight:
    pipetting: (better word)
      component(Component): 
      alias: (default value)
      measured_volume:
      density:
      container_mass:
      net_mass:
      brutto_mass:
      molecular_weight:
    mixing:
      mixed_aliases:
      alias: (default value based on mixed_aliases)
      mixing_time:
      container_type:
      temperature:
      rotation_speed:
```
